### ISSUE TITLE
Show Json Data in Seperated page

### ISSUE THREAD

**Issue by SajadJalilian** [SajadJalilian/RealMoney#5]
Right now we show all the data on the main page and we use a button.
This is not good practice because we have also data. We should create a separate page to show the data and shod than some kind of table to visualize better.

**Comment by raanaweysi** [comment]
Ok
I try solve this issue. You want to i resolve issue in this branch or i create new branch for issue?

**Comment by SajadJalilian** [comment]
This branch is fine. You can do in in this branch. Thank you
